---
- name: Add user james on webservers
  hosts: webservers
  become: true

  tasks:
    - name: Ensure user james exists
      ansible.builtin.user:
        name: james
        state: present
        create_home: yes
